### ISSUE TITLE
Custom Fonts (Google Fonts) in Customizing

### ISSUE THREAD

**Issue by MajorTomDE** [prtksxna/zuari#108] opened 2020-04-19 12:41 UTC
Hey,

it would be great if you can implement a function within the customizing to easy change the font families.

Otherwise your theme is really great. I love the simple design.

Greating from Germany.
Tom

**Comment by prtksxna** [comment] 2020-04-19 13:30
I am glad you like the theme 😊

Allowing Google fonts was on of the first things that I wanted to do in the theme (actually second — #2) but I just haven't gotten around to doing it yet.

I'll close this issue (since its a duplicate of #2) and encourage you to subscribe to that one to get an update.

**Closed by prtksxna** 2020-04-19 13:30 UTC

**Comment by MajorTomDE** [comment] 2020-04-22 20:13
Great! Thanks. I did not seen #2
